### ISSUE TITLE
Why is the default log mode the debug mode?

### ISSUE THREAD

**Issue by linux-gcc** [oamg/leapp#743]
Why is the default leapp log mode the debug mode?

**Comment by pirat89** [comment]
Hi, good question. I guess that it's because the log file without debug logs is not valuable from our point of view. The INFO and higher levels doesn't tell so much when any investigation is needed and why usually people look at the generated log file - at least in case of leapp. Debug data is usually requirement in overwhelming majority of cases we investigate and we would have to ask people almost everytime to run leapp again with the `--debug` option to give us wanted data otherwise. Regarding the number of cases we have to investigate, having the debug level log as a default has become right as rain.

**Comment by fernflower** [comment]
Closing, please reopen if needed.
